{
 "title": "Tomcat Monitoring",
 "description": "Dashboard for JVM metrics with Prometheus / JMX Exporter",
 "tags": [
  "JVM",
  "tomcat"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_bytes_max,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "requestcount",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(tomcat_requestprocessor_request_count{instance=~\"$instance\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Requestcount Current",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(tomcat_requestprocessor_request_count{instance=~\"$instance\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Requestcount  Average",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(tomcat_requestprocessor_request_count{instance=~\"$instance\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Errorcount",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(tomcat_requestprocessor_error_count{instance=~\"$instance\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Jvm Max Mem heap",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Mem Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",instance=~\"$instance\"}",
     "legendFormat": "已经使用的堆内存"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",instance=~\"$instance\"}",
     "legendFormat": "已经使用的非堆内存"
    }
   ]
  },
  {
   "title": "Mem Committed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{area=\"heap\",instance=~\"$instance\"}",
     "legendFormat": "已经提交的堆内存"
    },
    {
     "expr": "jvm_memory_bytes_committed{area=\"nonheap\",instance=~\"$instance\"}",
     "legendFormat": "已经提交的非堆内存"
    }
   ]
  },
  {
   "title": "Pool committed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Code Cache\",instance=~\"$instance\"} ",
     "legendFormat": "Code Cache"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Metaspace\",instance=~\"$instance\"}",
     "legendFormat": "Metaspace"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Compressed Class Space\",instance=~\"$instance\"}",
     "legendFormat": "Compressed Class Space"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"PS Eden Space\",instance=~\"$instance\"}",
     "legendFormat": "PS Eden Spac"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"PS Survivor Space\",instance=~\"$instance\"}",
     "legendFormat": "PS Survivor Space"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"PS Old Gen\",instance=~\"$instance\"}",
     "legendFormat": "PS Old Gen"
    }
   ]
  },
  {
   "title": "Pool User",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Code Cache\",instance=~\"$instance\"}",
     "legendFormat": "Code Cache"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Metaspace\",instance=~\"$instance\"}",
     "legendFormat": "Metaspace"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Compressed Class Space\",instance=~\"$instance\"}",
     "legendFormat": "Compressed Class Space"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"PS Eden Space\",instance=~\"$instance\"}",
     "legendFormat": "PS Eden Space"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"PS Survivor Space\",instance=~\"$instance\"}",
     "legendFormat": "PS Survivor Space"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"PS Old Gen\",instance=~\"$instance\"}",
     "legendFormat": "PS Old Gen"
    }
   ]
  },
  {
   "title": "Count Gc",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{gc=\"PS Scavenge\",instance=~\"$instance\"}",
     "legendFormat": "PS Scavenge"
    },
    {
     "expr": "jvm_gc_collection_seconds_sum{gc=\"PS Scavenge\",instance=~\"$instance\"} ",
     "legendFormat": "PS Scavenge SUM"
    },
    {
     "expr": "jvm_gc_collection_seconds_count{gc=\"PS MarkSweep\",instance=~\"$instance\"}",
     "legendFormat": "PS MarkSweep"
    },
    {
     "expr": "jvm_gc_collection_seconds_sum{gc=\"PS MarkSweep\",instance=~\"$instance\"}",
     "legendFormat": "PS MarkSweep SUM"
    }
   ]
  },
  {
   "title": "threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=~\"$instance\"}",
     "legendFormat": "当前的线程连接数"
    },
    {
     "expr": "jvm_threads_started_total{instance=~\"$instance\"}",
     "legendFormat": "线程数总和"
    },
    {
     "expr": "jvm_threads_daemon{instance=~\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak{instance=~\"$instance\"}",
     "legendFormat": "线程峰值"
    },
    {
     "expr": "jvm_threads_deadlocked{instance=~\"$instance\"}",
     "legendFormat": "deadlocked"
    },
    {
     "expr": "jvm_threads_deadlocked_monitor{instance=~\"$instance\"}",
     "legendFormat": "deadlocked_monitor"
    }
   ]
  },
  {
   "title": "Classes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{instance=~\"$instance\"}",
     "legendFormat": "已经加载的类"
    },
    {
     "expr": "jvm_classes_loaded_total{instance=~\"$instance\"}",
     "legendFormat": "加载类的总和"
    },
    {
     "expr": "jvm_classes_unloaded_total{instance=~\"$instance\"}",
     "legendFormat": "已卸载的类"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(tomcat_requestprocessor_received_bytes{instance=~\"$instance\"}[10m]))",
     "legendFormat": "input"
    },
    {
     "expr": "sum(irate(tomcat_requestprocessor_sent_bytes{instance=~\"$instance\"}[10m]))",
     "legendFormat": "output"
    }
   ]
  }
 ]
}